Mengubah kembalian Employee dengan Response
achmadynasution/oims pull request #5
Opened 2018-11-29 17:29 UTC by achmadynasution

2018-12-11 05:49 UTC, ekomanurung requested changes

2018-12-11 05:49 UTC, ekomanroe commented on futureprogram/src/main/java/com/oims/futureprogram/controller/EmployeeController.java
> +    public List<Employee> getEmployee() { return employeeService.getEmployee(); }
blum diwrap ke Response ya.??

2018-12-11 05:49 UTC, ekomanroe commented on futureprogram/src/main/java/com/oims/futureprogram/controller/RoleController.java
> +    public Optional<Role> getRoleByName(@PathVariable String roleName) {
ini juga

2018-12-15 03:37 UTC, achmadynasution commented on futureprogram/src/main/java/com/oims/futureprogram/controller/EmployeeController.java
> +    public List<Employee> getEmployee() { return employeeService.getEmployee(); }
ohh ini salah pull bang sry

2018-12-15 03:37 UTC, closed without merging